name: win_lin

on:
  push:
    branches: [ "main","test1" ]

permissions:
  contents: read

jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true

    - name: STAGE pip upgrade
      run: python -m pip install --upgrade pip

    - name: STAGE requirements
      run: pip install -r requirements.txt

    - name: STAGE pyinstaller
      run: pip install pyinstaller==5.7.0

    - name: STAGE run pyinstaller
      run: "pyinstaller.run.bat"
      shell: cmd

    - uses: actions/upload-artifact@v3
      with:
        name: dude-win
        path: "./dist/dude.exe"

  build-lin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true

    - name: STAGE pip upgrade
      run: python -m pip install --upgrade pip

    - name: STAGE requirements
      run: pip install -r requirements.txt

    - name: STAGE install pyinstaller
      run: pip install pyinstaller==5.7.0
    
    - name: STAGE find myself
      run: pwd
    
    - name: STAGE find python
      run: find $pythonLocation -name libpython3*
    
    - name: STAGE strip libs
      run: find $pythonLocation -name *.so* -type f -exec strip {} \;

    - name: STAGE run pyinstaller
      run: bash "pyinstaller.run.sh"

    - name: STAGE check executable file
      run: ls -l ./dist/dude

    - uses: actions/upload-artifact@v3
      with:
        name: dude-lin
        path: "./dist/dude"
