name: win_lin

on:
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  set-version:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        check-latest: true
  
    - name: generate version number
      working-directory: ./scripts
      run: bash "version.gen.sh"

    - uses: actions/upload-artifact@v3
      with:
        name: version
        path: ./src/version.txt
  
  build-lin:
    needs: [set-version]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        check-latest: true

    - name: pip upgrade
      run: python -m pip install --upgrade pip

    - name: install requirements
      run: pip install -r requirements.txt

    - name: Download version artifact
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./src
        
    - name: strip python binaries
      run: find $pythonLocation -name *.so* -type f -exec strip {} \;
    
    - name: run Nuitka
      working-directory: ./scripts
      run: bash "nuitka.run.sh"
    
    - name: upload binary
      uses: actions/upload-artifact@v3
      with:
        name: dude-lin
        path: dude
        
  build-win:
    needs: [set-version]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        check-latest: true

    - name: pip upgrade
      run: python -m pip install --upgrade pip

    - name: install requirements
      run: pip install -r requirements.txt
    
    - name: Download version artifact
      id: version
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./src
    
    - name: run Nuitka
      working-directory: ./scripts
      run: "nuitka.run.bat"
      shell: cmd

    - name: upload binary
      uses: actions/upload-artifact@v3
      with:
        name: dude-win
        path: |
          dude.exe
          dudegui.exe

  release:
    permissions: write-all
    runs-on: ubuntu-20.04
    needs: [build-lin, build-win]
    
    steps:
    - name: Download version
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./
    
    - name: Read version
      id: version
      run: echo "version=$(cat ./version.txt)" >> $GITHUB_OUTPUT

    - name: Download linux build
      uses: actions/download-artifact@v3
      with:
        name: dude-lin
        path: ./

    - name: chmod
      run: |
        chmod 777 ./dude
        tar -czvf dude.lin.${{ steps.version.outputs.version }}.tgz dude
        zip dude.win.${{ steps.version.outputs.version }}.zip dude.exe dudegui.exe
        
    - name: Download windows build
      uses: actions/download-artifact@v3
      with:
        name: dude-win
        path: ./

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_title: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: true
        files: |
            dude.lin.${{ steps.version.outputs.version }}.tgz
            dude.win.${{ steps.version.outputs.version }}.zip
    
