name: win_lin

on:
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  set-version:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        check-latest: true
  
    - name: STAGE gen version
      working-directory: ./scripts
      run: bash "version.gen.sh"

    - uses: actions/upload-artifact@v3
      with:
        name: version
        path: ./src/version.txt
  
  release:
    permissions: write-all
    runs-on: ubuntu-20.04
    needs: [set-version]
    
    steps:
    - name: Download version
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./
    
    - name: Read version
      id: version
      run: echo "version=$(cat ./version.txt)" >> $GITHUB_OUTPUT

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_title: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: true
        files: version.txt
    
