name: win_lin

on:
  push:
    branches: [ "main","test1" ]

permissions:
  contents: read

jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true

    - name: STAGE pip upgrade
      run: python -m pip install --upgrade pip

    - name: STAGE requirements
      run: pip install -r requirements.txt

    - name: STAGE install Nuitka
      run: pip install nuitka==1.4.1
      
    - name: STAGE install ordered-set
      run: pip install ordered-set==4.1.0

    - name: STAGE install zstandard
      run: pip install zstandard==0.18.0

    - name: STAGE run Nuitka
      run: "nuitka.run.bat"
      shell: cmd

    - uses: actions/upload-artifact@v3
      with:
        name: dude-win
        path: |
          dude.exe
          dudegui.exe

  build-lin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        check-latest: true

    - name: STAGE pip upgrade
      run: python -m pip install --upgrade pip

    - name: STAGE requirements
      run: pip install -r requirements.txt

    - name: STAGE find python
      run: find $pythonLocation -name libpython3*
    
    - name: STAGE strip libs
      run: find $pythonLocation -name *.so* -type f -exec strip {} \;
      
    - name: STAGE install Nuitka
      run: pip install nuitka==1.4.1
      
    - name: STAGE install ordered-set
      run: pip install ordered-set==4.1.0
      
    - name: STAGE install zstandard
      run: pip install zstandard==0.18.0
    
    - name: STAGE run Nuitka
      run: bash "nuitka.run.sh"

    - uses: actions/upload-artifact@v3
      with:
        name: dude-lin
        path: dude
