name: win_lin_release

on:
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  win-gen-version-build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        check-latest: true

    - name: pip upgrade
      run: python -m pip install --upgrade pip

    - name: install requirements
      run: pip install -r requirements.txt

    - name: generate version number
      working-directory: ./scripts
      run: "version.gen.bat"
      shell: cmd

    - name: version upload
      uses: actions/upload-artifact@v3
      with:
        name: version
        path: ./src/version.txt

    - name: run nuitka
      working-directory: ./scripts
      run: "nuitka.run.bat"
      shell: cmd

    - name: upload binary
      uses: actions/upload-artifact@v3
      with:
        name: dude-win
        path: dude.exe

    - name: upload binary raw
      uses: actions/upload-artifact@v3
      with:
        name: dude-win-raw
        path: dude-raw.zip

  build-lin-release:
    permissions: write-all
    needs: [win-gen-version-build]
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        check-latest: true

    - name: pip upgrade
      run: python -m pip install --upgrade pip

    - name: install requirements
      run: pip install -r requirements.txt

    - name: version download
      uses: actions/download-artifact@v3
      with:
        name: version
        path: ./src

    - name: strip python binaries
      run: find $pythonLocation -name *.so* -type f -exec strip {} \;

    - name: run nuitka
      working-directory: ./scripts
      run: bash "nuitka.run.sh"

    - name: upload binary
      uses: actions/upload-artifact@v3
      with:
        name: dude-lin
        path: dude

    - name: version read
      id: version
      run: echo "version=$(cat ./src/version.txt)" >> $GITHUB_OUTPUT

    - name: pack linux
      run: |
        chmod 777 ./dude
        tar -czvf dude.${{ steps.version.outputs.version }}.portable.linux.tgz dude
        rm ./dude

    - name: download windows build
      uses: actions/download-artifact@v3
      with:
        name: dude-win
        path: ./

    - name: pack windows
      run: zip dude.${{ steps.version.outputs.version }}.portable.windows.zip dude.exe

    - name: download windows build raw
      uses: actions/download-artifact@v3
      with:
        name: dude-win-raw
        path: ./

    - name: rename windows raw
      run: mv ./dude-raw.zip ./dude.${{ steps.version.outputs.version }}.portable.windows.raw.zip

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        files: |
            dude.${{ steps.version.outputs.version }}.portable.linux.tgz
            dude.${{ steps.version.outputs.version }}.portable.windows.zip
            dude.${{ steps.version.outputs.version }}.portable.windows.raw.zip
